### ISSUE TITLE
Invalid Procedure call || ERROR : Object doesn't support this property or method

### ISSUE THREAD

**Issue by thefoofighter** [ReinhardC/softimage#1]
Hi,

I am an XSI user but new to the world of 3D printing and rather than converting OBJ's to STL's for upload to thingiverse I was hoping to use your plugin to simply export an STL but i get the following error:

// ERROR : Invalid procedure call or argument

![image](https://user-images.githubusercontent.com/1424288/63898196-2c129b00-c9f8-11e9-9e06-65a58aa60fa8.png)

I installed as instructed and created a cube and tried to export as STL from the export menu.

have you any ideas what might cause this?

I am using the latest release from here on Github.

Thanks for the plugin 👍

**Comment by thefoofighter** [comment]
Ok so I threw on Softimage to have a look at the issue again and it seems that the "Invalid Procedure Call" error may have only required a softimage or system reboot as it was gone today.

However that did run me into another error : "ERROR : Object doesn't support this property or method"

I managed to fix the issue by changing the line 498 from:

`bExportBinary = (GetValue("preferences.File Format Options.STL_Format") = 0);`

to

`bExportBinary = GetValue("preferences.File Format Options.STL_Format");`

I dont know why but double setting at least this value on my system causes the error above.

I don't know if this is a valid fix or not but i can make a pull request if you like, otherwise it doesnt matter, someone else with a similar issue might come across this and fix it for themselves.

Thanks again for the plugin <3

**Comment by ReinhardC** [comment]
(crossposting xd) 

> luceric: it was probably meant to be bExportBinary = (GetValue("preferences.FileFormatOptions.STL_Format") == 0);
>which, if that's correct, would be the oposite of your fix

Thanks for the heads up (and using the plugin) !
Indeed "==0" as luceric mentioned. Fixed it at some point but didn't upload any new releases after that!

(new release is uploaded now)

**Comment by thefoofighter** [comment]
Cool, confirmed working :) Thanks for the fix and additional feature.
